JuliePro/JuliePro/Controllers/ObjectivesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JuliePro.Data;
using JuliePro.Models;

namespace JuliePro.Controllers
{
    public class ObjectivesController : Controller
    {
        private readonly JulieProDbContext _baseDonnees;

        public ObjectivesController(JulieProDbContext baseDonnees)
        {
            _baseDonnees = baseDonnees;
        }

        // GET: Objectives
        public async Task<IActionResult> Index()
        {
            return _baseDonnees.Objectives != null ?
                        View(await _baseDonnees.Objectives.ToListAsync()) :
                        Problem("Entity set 'JulieProDbContext.Objectives'  is null.");
        }

    
}
}

JuliePro/JuliePro/Controllers/SpecialityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JuliePro.Data;
using JuliePro.Models;

namespace JuliePro.Controllers
{
    public class SpecialityController : Controller
    {
        private  JulieProDbContext _baseDonnees { get; set; }

        public SpecialityController(JulieProDbContext baseDonnes)
        {
            _baseDonnees = baseDonnes;
            
        }

        // GET: Speciality
        public async Task<IActionResult> Index()
        {
             List<Speciality> specialities = await _baseDonnees.Specialities.OrderBy(z=>z.Name).ToListAsync();
            return View(specialities);
        }

        // GET: Speciality/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _baseDonnees.Specialities == null)
            {
                return NotFound();
            }

            var speciality = await _baseDonnees.Specialities
                .FirstOrDefaultAsync(m => m.Id == id);
            if (speciality == null)
            {
                return NotFound();
            }

            return View(speciality);
        }

        // GET: Speciality/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Speciality/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Id")] Speciality speciality)
        {
            if (ModelState.IsValid)
            {
                _baseDonnees.Add(speciality);
                await _baseDonnees.SaveChangesAsync();
                TempData["Succes"] = $"Speciality {speciality.Name} added";
                return RedirectToAction(nameof(Index));
            }
            return View(speciality);
        }

        // GET: Speciality/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _baseDonnees.Specialities == null)
            {
                return NotFound();
            }

            var speciality = await _baseDonnees.Specialities.FindAsync(id);
            if (speciality == null)
            {
                return NotFound();
            }
            return View(speciality);
        }

        // POST: Speciality/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, [Bind("Name,Id")] Speciality speciality)
        {
            if (id != speciality.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _baseDonnees.Update(speciality);
                    await _baseDonnees.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SpecialityExists(speciality.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(speciality);
        }

        // GET: Speciality/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
        


            if (id == null || _baseDonnees.Specialities == null)
            {
                return NotFound();
            }

            var speciality = await _baseDonnees.Specialities
                .FirstOrDefaultAsync(m => m.Id == id);
            if (speciality == null)
            {
                return NotFound();
            }


            return View(speciality);
        }

        // POST: Speciality/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            
           

                if (_baseDonnees.Specialities == null)
            {
                return Problem("Entity set 'JulieProDbContext.Specialities'  is null.");
            }
            var speciality = await _baseDonnees.Specialities.FindAsync(id);
            if (speciality != null)
            {
                _baseDonnees.Specialities.Remove(speciality);
            }
            
            await _baseDonnees.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
      

        private bool SpecialityExists(int? id)
        {
          return (_baseDonnees.Specialities?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

JuliePro/JuliePro/Controllers/TrainersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JuliePro.Data;
using JuliePro.Models;

namespace JuliePro.Controllers
{
    public class TrainersController : Controller
    {
        private readonly JulieProDbContext _baseDonnees;

        public TrainersController(JulieProDbContext baseDonnees)
        {
           _baseDonnees = baseDonnees;
        }

        // GET: Trainers
        public async Task<IActionResult> Index()
        {
             List<Trainer>trainers = await _baseDonnees.Trainers.OrderBy(x => x.FirstName ).Include(x=>x.Speciality).ToListAsync();
            return View(trainers);
        }

        // GET: Trainers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
         Trainer trainers = await _baseDonnees.Trainers.Where(x=>x.Id==id).Include(x=>x.Speciality).FirstAsync();
            return View(trainers);
        }

        // GET: Trainers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Trainers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FirstName,LastName,Email,Photo,Id,SpecialityId")] Trainer trainer)
        {
            if (ModelState.IsValid)
            {
                _baseDonnees.Add(trainer);
                await _baseDonnees.SaveChangesAsync();
                TempData["Success"] = $"{trainer.FirstName} trainer added";
                return RedirectToAction(nameof(Index));
            }
            return View(trainer);
        }

        // GET: Trainers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _baseDonnees.Trainers == null)
            {
                return NotFound();
            }

            var trainer = await _baseDonnees.Trainers.FindAsync(id);
            if (trainer == null)
            {
                return NotFound();
            }
            return View(trainer);
        }

        // POST: Trainers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FirstName,LastName,Email,Photo,Id,SpecialityId")] Trainer trainer)
        {
            if (id != trainer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _baseDonnees.Update(trainer);
                    await _baseDonnees.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TrainerExists(trainer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(trainer);
        }

        // GET: Trainers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _baseDonnees.Trainers == null)
            {
                return NotFound();
            }

            var trainer = await _baseDonnees.Trainers
                .FirstOrDefaultAsync(m => m.Id == id);
            if (trainer == null)
            {
                return NotFound();
            }

            return View(trainer);
        }

        // POST: Trainers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_baseDonnees.Trainers == null)
            {
                return Problem("Entity set 'JulieProDbContext.Trainer'  is null.");
            }
            var trainer = await _baseDonnees.Trainers.FindAsync(id);
            if (trainer != null)
            {
                _baseDonnees.Trainers.Remove(trainer);
            }
            
            await _baseDonnees  .SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TrainerExists(int id)
        {
          return (_baseDonnees.Trainers?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

JuliePro/JuliePro/Views/Shared/_ButtonCreat.cshtml
 @model int
 <div class="col-12">
    @if (Model == 0)
    {
     <button type="submit" value="Create" class="btn btn-success w-100" ><i class="fa-solid fa-plus"></i> &nbsp;&nbsp; Create</button>
                    
    }
   
    
</div>
<div class="col-12">
    <a asp-action="Index" class="btn btn-secondary w-100"><i class="fa-solid fa-circle-arrow-left"></i> &nbsp;Back to list</a>
</div>

JuliePro/JuliePro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JuliePro</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css"  asp-append-version="true"/>
    <link rel="stylesheet" href="~/Juliepro.styles.css" asp-append-version="true" />
     <link href="~/fontawesome/css/all.css" rel="stylesheet">
    <style>
      .accordion-item { border: 1px solid rgba(0,0,0,.125) }
    </style>
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
      <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/imagesLayout/tile.png" style="width:80%" /></a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
          <ul class="navbar-nav flex-grow-1">
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Admin
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" asp-controller="Trainers" asp-action="Index">Trainers</a></li>
                <li><a class="dropdown-item" asp-controller="Speciality" asp-action="Index">Specialities</a></li>
                  <li><a class="dropdown-item" asp-controller="Objectives" asp-action="Index">Objectives</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <div class="container">
    <main role="main" class="pb-3">
      @RenderBody()
    </main>
  </div>

  <footer class="border-top footer text-muted bg-primary">
    <div class="container">
      &copy; 2021 - JuliePro - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
  </footer>
  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
  @await RenderSectionAsync("Scripts", required: false)
</body>
</html>